name: VCID_environment
version: 1.0
channels:
  - plotly
  - anaconda
  - bioconda
  - conda-forge
dependencies:
  - bamaddrg=9baba65f88228e55639689a3cea38dd150e6284f=h4dc6686_2
  - bamtools=2.5.2=hdcf5f25_5
  - bcftools=1.20=h8b25389_1
  - bioconductor-genomicalignments=1.38.0=r43ha9d7317_1
  - bioconductor-genomicranges=1.54.1=r43ha9d7317_2
  - bioconductor-rsamtools=2.18.0=r43hf17093f_2
  - bioconductor-rtracklayer=1.62.0=r43ha9d7317_1
  - curl=8.8.0=he654da7_1
  - freebayes=1.3.8=h6a68c12_2
  - igraph=0.10.13=hef0740d_0
  - plotly=6.0.0=py_0
  - r-data.table=1.15.2=r43h029312a_0
  - r-dplyr=1.1.4=r43h0d4f4ea_1
  - r-ggplot2=3.5.1=r43hc72bb7e_1
  - r-gridextra=2.3=r43hc72bb7e_1006
  - r-htmltools=0.5.8.1=r43ha18555a_1
  - r-httr=1.4.7=r43hc72bb7e_1
  - r-optparse=1.7.5=r43hc72bb7e_1
  - r-plotly=4.11.0=r43hc72bb7e_0
  - r-readr=2.1.5=r43h0d4f4ea_1
  - r-reshape2=1.4.4=r43h0d4f4ea_4
  - r-scales=1.3.0=r43hc72bb7e_1
  - r-stringr=1.5.1=r43h785f33e_1
  - r-tictoc=1.2.1=r43hc72bb7e_1
  - r-tidyr=1.3.1=r43h0d4f4ea_1
  - r-yaml=2.3.10=r43hdb488b9_0
  - samtools=1.20=h50ea8bc_1
  - yaml=0.2.5=h7f98852_2